# Reference: https://github.com/repository-settings/app

_extends: .github

repository:
  name: client-library
  description: Native client libraries for integrating with mytiki.com
  homepage: https://docs.mytiki.com/reference/client-library-overview
  topics: mobile, web, library
  private: false
  has_projects: false
  has_discussions: false
  has_issues: false

teams:
  - name: sysadmin
    permission: admin
  - name: engineering
    permission: push
  - name: product
    permission: triage
  - name: frontend
    permission: push

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []
